# Generated by Django 3.2.9 on 2021-12-07 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='course',
            new_name='the_course',
        ),
    ]
