# Generated by Django 3.2.9 on 2021-12-07 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('course', '0005_rename_course_comment_the_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='message')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create_time')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('the_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
    ]
